### ISSUE TITLE
Codebook Collapse for Mimi Codec

### ISSUE THREAD

**Issue by gmltmd789** [yangdongchao/RSTnet#2]
Hi,

First of all, thank you for providing such excellent code.

The Mimi-codec you uploaded has been extremely helpful to me.

I have trained your code using the LibriTTS dataset and tested it. However, I noticed that all the generated wav files collapse into a single index.

I would like to ask if you have encountered a similar issue during your training attempts and how you resolved it.

**Comment by yangdongchao** [comment]
> Hi,
> 
> First of all, thank you for providing such excellent code.
> 
> The Mimi-codec you uploaded has been extremely helpful to me.
> 
> I have trained your code using the LibriTTS dataset and tested it. However, I noticed that all the generated wav files collapse into a single index.
> 
> I would like to ask if you have encountered a similar issue during your training attempts and how you resolved it.

We find that we forget to add the gradient copy operation in core_vq.py. I have fix this issue. Can you try it again?

**Comment by gmltmd789** [comment]
Thank you for your response. I will try again.

**Comment by gmltmd789** [comment]
![image](https://github.com/user-attachments/assets/d8ec2d98-807c-427a-8f6f-36411b7eb0ed)

Hi,

I have run the modified code following your guidance.

However, as you can see, I observed that the loss curve appears to be quite unstable.

May I kindly ask if you have encountered a similar issue, and what dataset you used during your previous training efforts?

**Comment by yangdongchao** [comment]
> ![image](https://private-user-images.githubusercontent.com/49265950/374513315-d8ec2d98-807c-427a-8f6f-36411b7eb0ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTU4NTEsIm5iZiI6MTcyODU1NTU1MSwicGF0aCI6Ii80OTI2NTk1MC8zNzQ1MTMzMTUtZDhlYzJkOTgtODA3Yy00MjdhLThmNmYtMzY0MTFiN2ViMGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEwMTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDFiMDAxYTZhNmNhY2IyMjI4MDE4MGI5M2QyMjkzMzMzNTcwOWZmN2ZiZjgzNzBkZjExNDNjYmJkZDA4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SA-NcDmTz0FxM815-48n8VJZwv370EnL2CuihzjhSjY)
> 
> Hi,
> 
> I have run the modified code following your guidance.
> 
> However, as you can see, I observed that the loss curve appears to be quite unstable.
> 
> May I kindly ask if you have encountered a similar issue, and what dataset you used during your previous training efforts?

Hi, sorry for the delayed reply. 
I find that the original VQ is hard to use. Now, I am re-writing the SplitResidualVectorQuantizer class based on vector_quantize_pytorch. I find the loss can decrease now (by training 11810 steps, g_loss from 6.3 ---> 3). However, due to the limitation of GPU resources, I cannot train more steps now. But I will update the final results in the future.

**Comment by gmltmd789** [comment]
Thank you for your prompt and kind response.
I will try running the code you provided as soon as I have the resources available :)

**Comment by hdmjdp** [comment]
> Thank you for your prompt and kind response. I will try running the code you provided as soon as I have the resources available :)

have you got good wav as the moshi's result？

**Comment by gmltmd789** [comment]
> > Thank you for your prompt and kind response. I will try running the code you provided as soon as I have the resources available :)
> 
> have you got good wav as the moshi's result？

Hello. Due to my involvement in another project, I currently lack the resources to verify and modify the reproduction code, so it has been put on hold.
